
Welcome to my Lab 2 repository for Quantitative Biology BIOL 275 at MSUM.

## Lab objectives

The objectives of this lab are:
<<<<<<< HEAD
=======

>>>>>>> 98cce924a2bde059c06ff8347c870de2e6eda865
- Use the console and source windows in RStudio
- Write and run code in an R script
- Document your R code with comments
- Transfer code from an R script to an R Markdown document
- Craft a narrative combining text explanation, code, and graphs
<<<<<<< HEAD
=======


>>>>>>> 98cce924a2bde059c06ff8347c870de2e6eda865
## Repository contents

The repository contains the following scripts:

- [calculator.R](calculator.R)
- [Lab 2 Report](assignment.md)

## Instructions for knitting

Your actual README document must be a Markdown file. This one is an R Markdown file.

When you are done editing this document, click the Knit button in the Source Pane. RStudio will then convert this into a .md file and give you a preview in a separate window. Make sure everything looks okay and then close the preview window.

## R Markdown

This README is an R Markdown document (.Rmd), which means you can use markdown syntax and you can embed code chunks.

Here is a list of resources for helping you write R Markdown documents:

- In the Go to the **Help** menu and select **Markdown Quick Reference**
- [Basic Syntax](https://www.markdownguide.org/basic-syntax/) on the Markdown Guide website


